Repository OCA/search-engine, pull requests merged in 2020-12, with the labels that each got.

#66 [13.0] [IMP] connector_search_engine: avoid write on bindings when force export
  connector_search_engine/models/se_index.py
Labels: approved, bot is merging ⏳

#65 [13.0] [FIX] connector_search_engine: export cron priority
  connector_search_engine/data/ir_cron.xml
Labels: bot is merging ⏳

#64 [13.0][PORT] 47 from 12.0
  connector_elasticsearch/readme/CONTRIBUTORS.rst
  connector_search_engine/models/se_index_config.py
Labels: bot is merging ⏳, needs review

#68 [REF] migrate to new queue job
  connector_search_engine/__manifest__.py
  connector_search_engine/data/queue_job_channel_data.xml
  connector_search_engine/data/queue_job_function_data.xml
  connector_search_engine/models/se_binding.py
  connector_search_engine/models/se_index.py
Labels: approved, bot is merging ⏳
