Repository OCA/search-engine, pull requests merged in 2020-11, with the labels that each got.

#50 [13.0] Refactor tests and misc fix/imp
  .travis.yml
  connector_algolia/__manifest__.py
  connector_algolia/models/__init__.py
  connector_algolia/models/se_backend_algolia.py
  connector_algolia/models/se_index.py
  connector_elasticsearch/__manifest__.py
  connector_elasticsearch/demo/backend_demo.xml
  connector_elasticsearch/models/__init__.py
  connector_elasticsearch/models/se_index.py
  connector_elasticsearch/models/se_index_config.py
  connector_elasticsearch/security/se_index_config.xml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_delete.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_iter.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_no_objectID.yaml
  connector_elasticsearch/tests/docker-compose.elasticsearch.example.yml
  connector_elasticsearch/tests/test_connector_elasticsearch.py
  connector_search_engine/__manifest__.py
  connector_search_engine/models/__init__.py
  connector_search_engine/models/se_backend.py
  connector_search_engine/models/se_binding.py
  connector_search_engine/models/se_index.py
  connector_search_engine/models/se_index_config.py
  connector_search_engine/security/se_index_config.xml
  connector_search_engine/tests/models.py
  connector_search_engine/tests/models_mixin.py
  connector_search_engine/tests/test_all.py
  connector_search_engine/views/se_index_config.xml
  test-requirements.txt
Labels: approved, bot is merging ⏳, needs review

#53 se.binding: add data_display, compute size for algolia index binding
  connector_algolia/models/__init__.py
  connector_algolia/models/se_binding.py
  connector_algolia/tests/test_se_algolia.py
  connector_search_engine/models/se_binding.py
Labels: bot is merging ⏳, needs review

#58 Fix recompute JSON data using SUDO
  connector_search_engine/models/se_binding.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#51 Move tech_name field to server env mixin + fix env override of index_prefix_name
  connector_algolia/__manifest__.py
  connector_algolia/i18n/connector_algolia.pot
  connector_algolia/migrations/13.0.2.2.0/post-migrate.py
  connector_algolia/models/se_backend_algolia.py
  connector_elasticsearch/__manifest__.py
  connector_elasticsearch/i18n/connector_elasticsearch.pot
  connector_elasticsearch/migrations/13.0.2.1.0/post-migrate.py
  connector_elasticsearch/models/se_backend_elasticsearch.py
  connector_search_engine/i18n/connector_search_engine.pot
  connector_search_engine/migrations/12.0.3.2.0/post-migrate.py
  connector_search_engine/models/se_backend.py
  connector_search_engine/models/se_backend_spec_abstract.py
  connector_search_engine/models/se_index.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#62 [13.0][PORT] 45 from 12.0
  connector_algolia/components/adapter.py
  connector_elasticsearch/components/adapter.py
  connector_search_engine/components/adapter.py
Labels: bot is merging ⏳

#63 [12.0][REF] fix precommit issue
  connector_elasticsearch/demo/backend_demo.xml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_delete.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_iter.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_no_objectID.yaml
  connector_elasticsearch/tests/test_connector_elasticsearch.py
Labels: bot is merging ⏳

#45 [12.0][FIX] connector_algolia, connector_elastic inherit from se.backend.adapter
  connector_algolia/components/adapter.py
  connector_elasticsearch/components/adapter.py
  connector_search_engine/components/adapter.py
Labels: approved, bot is merging ⏳, ready to merge

#47 [12.0] Fix missing default values when creating an index.
  connector_elasticsearch/models/se_index_config.py
  connector_elasticsearch/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳
