Repository OCA/search-engine, pull requests merged in 2023-06, with the labels that each got.

#149 connector_search_engine: Fix missing create in view
  connector_search_engine/views/se_backend.xml
Labels: bot is merging ⏳

#150 connector_search_engine: fix ui issue on index tree
  connector_search_engine/views/se_backend.xml
  connector_search_engine/views/se_index.xml
Labels: bot is merging ⏳

#145 [16.0] migration connector elasticsearch
  .pre-commit-config.yaml
  connector_elasticsearch/__init__.py
  connector_elasticsearch/__manifest__.py
  connector_elasticsearch/components/adapter.py
  connector_elasticsearch/components/core.py
  connector_elasticsearch/demo/backend_demo.xml
  connector_elasticsearch/migrations/13.0.2.1.0/post-migrate.py
  connector_elasticsearch/models/__init__.py
  connector_elasticsearch/models/se_backend.py
  connector_elasticsearch/models/se_backend_elasticsearch.py
  connector_elasticsearch/models/se_index.py
  connector_elasticsearch/security/se_backend_elasticsearch.xml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_delete.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_delete_nonexisting_documents.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_iter.yaml
  connector_elasticsearch/tests/cassettes/TestConnectorElasticsearch.test_index_adapter_reindex.yaml
  connector_elasticsearch/tests/test_connector_elasticsearch.py
  connector_elasticsearch/tools/__init__.py
  connector_elasticsearch/tools/adapter.py
  connector_elasticsearch/views/se_backend.xml
  connector_elasticsearch/views/se_backend_elasticsearch.xml
  connector_elasticsearch/views/se_menu.xml
  requirements.txt
  setup/connector_elasticsearch/odoo/addons/connector_elasticsearch
  setup/connector_elasticsearch/setup.py
Labels: needs review, bot is merging ⏳

#146 16.0 add connector search engine jsonifier
  connector_search_engine_serializer_ir_export/README.rst
  connector_search_engine_serializer_ir_export/__init__.py
  connector_search_engine_serializer_ir_export/__manifest__.py
  connector_search_engine_serializer_ir_export/models/__init__.py
  connector_search_engine_serializer_ir_export/models/se_index.py
  connector_search_engine_serializer_ir_export/readme/CONTRIBUTORS.rst
  connector_search_engine_serializer_ir_export/readme/DESCRIPTION.rst
  connector_search_engine_serializer_ir_export/tests/__init__.py
  connector_search_engine_serializer_ir_export/tests/fixtures/ir_exports_test.xml
  connector_search_engine_serializer_ir_export/tests/test_serializer.py
  connector_search_engine_serializer_ir_export/tools/__init__.py
  connector_search_engine_serializer_ir_export/tools/serializer.py
  connector_search_engine_serializer_ir_export/views/se_index_view.xml
  setup/connector_search_engine_serializer_ir_export/odoo/addons/connector_search_engine_serializer_ir_export
  setup/connector_search_engine_serializer_ir_export/setup.py
Labels: needs review, bot is merging ⏳

#152 16.0 cse serializer better namming
  connector_search_engine/views/se_backend.xml
  connector_search_engine_serializer_ir_export/__manifest__.py
  connector_search_engine_serializer_ir_export/models/se_index.py
  connector_search_engine_serializer_ir_export/readme/DESCRIPTION.rst
  connector_search_engine_serializer_ir_export/tests/test_serializer.py
Labels: bot is merging ⏳

#153 [16.0] connector_search_engine: fix error with empty recordset
  connector_search_engine/models/se_binding.py
Labels: approved, bot is merging ⏳
