Repository OCA/search-engine, pull requests merged in 2023-09, with the labels that each got.

#156 [15.0][UPD] copier & pre-commit
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: approved

#130 [15.0] [MIG] connector_search_engine
  connector_search_engine/README.rst
  connector_search_engine/__init__.py
  connector_search_engine/__manifest__.py
  connector_search_engine/components/__init__.py
  connector_search_engine/components/adapter.py
  connector_search_engine/components/core.py
  connector_search_engine/components/deleter.py
  connector_search_engine/components/exporter.py
  connector_search_engine/components/mapper.py
  connector_search_engine/data/ir_cron.xml
  connector_search_engine/data/queue_job_channel_data.xml
  connector_search_engine/data/queue_job_function_data.xml
  connector_search_engine/i18n/connector_search_engine.pot
  connector_search_engine/models/__init__.py
  connector_search_engine/models/se_backend.py
  connector_search_engine/models/se_backend_spec_abstract.py
  connector_search_engine/models/se_binding.py
  connector_search_engine/models/se_binding_todelete.py
  connector_search_engine/models/se_index.py
  connector_search_engine/models/se_index_config.py
  connector_search_engine/readme/CHANGES.rst
  connector_search_engine/readme/CONTRIBUTORS.rst
  connector_search_engine/readme/DESCRIPTION.rst
  connector_search_engine/readme/HISTORY.rst
  connector_search_engine/readme/ROADMAP.rst
  connector_search_engine/security/connector_search_engine_security.xml
  connector_search_engine/security/ir.model.access.csv
  connector_search_engine/security/se_index_config.xml
  connector_search_engine/static/description/icon.png
  connector_search_engine/static/description/index.html
  connector_search_engine/tests/__init__.py
  connector_search_engine/tests/common.py
  connector_search_engine/tests/fixtures/ir_exports_test.xml
  connector_search_engine/tests/models.py
  connector_search_engine/tests/test_all.py
  connector_search_engine/views/se_backend.xml
  connector_search_engine/views/se_index.xml
  connector_search_engine/views/se_index_config.xml
  connector_search_engine/views/se_menu.xml
  requirements.txt
  setup/connector_search_engine/odoo/addons/connector_search_engine
  setup/connector_search_engine/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#157 16.0 improve code
  connector_elasticsearch/models/se_backend.py
  connector_search_engine/models/se_indexable_record.py
  connector_search_engine/security/connector_search_engine_security.xml
  connector_search_engine/security/ir.model.access.csv
Labels: bot is merging ⏳

#142 [FIX] connector_search_engine: fix exception message
  .pre-commit-config.yaml
  connector_search_engine/models/se_binding.py
Labels: approved, bot is merging ⏳
